### ISSUE TITLE
WebUSB.h Dependency Error in Arduino IDE - Circuit Playground Classic

### ISSUE THREAD

**Issue by epeach** [adafruit/CircuitPlaygroundFirmata#14]
This change (https://github.com/adafruit/CircuitPlaygroundFirmata/pull/9) introduced a WebUSB.h dependency for the Circuit Playground Classic boards. The WebUSB library needs to be manually added to Arduino IDE (https://github.com/webusb/arduino#getting-started). A teacher following the instructions at (https://learn.adafruit.com/circuit-playground-firmata/firmata-sketch) reported to Code.org that they were getting stuck flashing the firmware to their boards with the following error:
![Screenshot from 2022-01-07 10-33-20](https://user-images.githubusercontent.com/2959170/148590573-cc6503fe-2ab7-42d2-ab24-661aeec87413.png)
 
Our knowledge of sketch files is limited - is there a way to bundle this dependency with the *.ino file? If not, we propose adding additional instructions to (https://learn.adafruit.com/circuit-playground-firmata/firmata-sketch) that cover how to manually add the WebUSB library to the Arduino IDE.

CC-ing @aaronwaggener and @KylieModen for visibility.

**Comment by ladyada** [comment]
since webusb isnt a real library you have to install it manually and there's no dependancy manager for arduino sketches (whee!)

instructions are updated here
https://learn.adafruit.com/circuit-playground-firmata/firmata-sketch
please check em out and close if that works!

**Comment by epeach** [comment]
Looks awesome - thank you so much!
