### ISSUE TITLE
Missing break statements in Firmata CPG sketches?

### ISSUE THREAD

**Issue by GeorgBraun** [adafruit/CircuitPlaygroundFirmata#15]
Dear Adafruit,

Thanks a lot for providing CPG, CPG-Express and the Firmata-Python-Implementation!

I am going to use it in my computer science class where students learn to program in Python on PCs and use the CPG to do some sensor data aquisition loops.

I did the tutorial on https://learn.adafruit.com/circuit-playground-firmata?view=all with the CPG Classic and all went fine.

Thanks a lot for providing this.

Looking through the code in `CircuitPlaygroundFirmata.ino` and `CircuitPlaygroundFirmata_Express_CodeOrg.ino`, I realized that there might be some missing `break` statements. Here they are:

**File `CircuitPlaygroundFirmata.ino`**

* in front of [`case CP_TONE:`](https://github.com/adafruit/CircuitPlaygroundFirmata/blob/e290007e2558fcb15ffa6c8667671451ff488eb7/CircuitPlaygroundFirmata/CircuitPlaygroundFirmata.ino#L605)
* in front of [`case CP_SENSECOLOR:`](https://github.com/adafruit/CircuitPlaygroundFirmata/blob/e290007e2558fcb15ffa6c8667671451ff488eb7/CircuitPlaygroundFirmata/CircuitPlaygroundFirmata.ino#L709)

**File `CircuitPlaygroundFirmata_Express_CodeOrg.ino`**

* in front of [`case CP_TONE:`](https://github.com/adafruit/CircuitPlaygroundFirmata/blob/e290007e2558fcb15ffa6c8667671451ff488eb7/CircuitPlaygroundFirmata_Express_CodeOrg/CircuitPlaygroundFirmata_Express_CodeOrg.ino#L870)

Best regards,
&nbsp;Georg

**Comment by ladyada** [comment]
good eyes! could you submit a PR?

**Comment by GeorgBraun** [comment]
Done. This was my first one on GitHub. Hope everything is okay.

**Comment by ladyada** [comment]
looks great :) nice work!

**Comment by caternuson** [comment]
indeed. fix has been PR'd. nothing for me to do here but say thanks! :)
