### ISSUE TITLE
Fail to download on circuit playground express

### ISSUE THREAD

**Issue by sung-park** [adafruit/CircuitPlaygroundFirmata#3]
Can I download this firmata to circuit playground express?

I tried on my windows and mac, but both are failed.

**Comment by ladyada** [comment]
nope it is not supported yet!
no ETA

**Comment by jfrux** [comment]
@ladyada Any major hurdles in implementing this for the Express?  Aside from the time it takes to review the sketch?

Trying to figure out if it's worth my time to work on a fork?

**Comment by ladyada** [comment]
hiya we're working on fixing up microphone support for express, then we can do firmata

**Comment by jfrux** [comment]
I’m new customer of Adafruit. Love what you are doing! I appreciate you guys very much. Thanks!

--
Joshua F. Rountree | UX Developer
The E.W. Scripps Company
312 Walnut Street, Suite 2800, Floor 29th, Office 29W109
Cincinnati, Ohio 45202-4024
(513) 977-3840 (office, M-F, 7a-4p)
(513) 827-7936 (mobile)

**Comment by ladyada** [comment]
this was done!
